"""Leave-one-out filter for code-dreamed tasks (Week 8 v2, CEO's α+δ synthesis).

Where Week 8 v1's filter asked "can Volcan memorize these demos?" and let
inconsistent LLM-hallucinated tasks through, this filter asks the stronger
question: "given N-1 demos, can Volcan predict the N-th demo correctly?"

Because the demos here were generated by a deterministic Python function, any
failure is capacity-bounded rather than consistency-bounded — if Volcan can't
leave-one-out, the rule is too hard for our current weights, not "broken."

This makes the accepted corpus a CURRICULUM: only tasks Volcan is almost
smart enough to solve from 3 examples make it into the Gold Dataset. Training
on this curriculum should avoid the "gradient collapse" we saw in Weeks 4-7
where the model got stuck at 52% pretraining accuracy because most training
pairs were either too easy (memorized instantly) or too hard (random to it).
"""

from __future__ import annotations

import time
from dataclasses import dataclass

import torch

from .arc import Example, Task, grid_to_onehot, grids_equal, onehot_to_grid
from .training_volcan import overfit_volcan_single_task, predict_volcan
from .volcan_cell import VolcanCell, VolcanConfig


@dataclass
class LOOFilterResult:
    """Outcome of the leave-one-out filter."""

    passed: bool
    demos_memorized: int   # how many training demos (3) the model overfit
    held_out_correct: bool  # whether the held-out demo was predicted exactly
    elapsed_sec: float
    reason: str


def leave_one_out_filter(
    task: Task,
    *,
    num_train_demos: int = 3,
    max_steps: int = 120,
    time_budget_sec: float = 30.0,
    phase_a_max: int = 6,
    phase_b_steps: int = 16,
    mlp_hidden: int = 128,
    device: str = "cpu",
    seed: int = 0,
) -> LOOFilterResult:
    """Train Volcan on task.train[:num_train_demos]; predict task.train[num_train_demos].

    Expected shape: task has ≥ num_train_demos + 1 training pairs. The last
    one is held out from training and used as the LOO target.

    Pass criteria:
      - Training demos are memorized (not strictly required — we mostly care
        about the held-out prediction)
      - The held-out demo's predicted output matches its true output exactly
      - Total wall time is under `time_budget_sec`
    """
    # Structural check.
    if task.num_train < num_train_demos + 1:
        return LOOFilterResult(
            passed=False, demos_memorized=0, held_out_correct=False,
            elapsed_sec=0.0,
            reason=f"need ≥{num_train_demos + 1} demos, got {task.num_train}",
        )

    # Build a "training task" with just the first num_train_demos pairs, plus
    # the held-out pair tucked into .test so it doesn't get seen during training.
    held_out = task.train[num_train_demos]
    train_only = Task(
        task_id=task.task_id + "_loo",
        train=task.train[:num_train_demos],
        test=[],
    )

    torch.manual_seed(seed)
    cfg = VolcanConfig(mlp_hidden=mlp_hidden)
    model = VolcanCell(cfg).to(device)

    t0 = time.time()
    try:
        log = overfit_volcan_single_task(
            model, train_only,
            num_steps=max_steps,
            phase_a_max=phase_a_max,
            phase_b_steps=phase_b_steps,
            device=device,
            log_every=max_steps,  # silent
        )
    except Exception as e:
        return LOOFilterResult(
            passed=False, demos_memorized=0, held_out_correct=False,
            elapsed_sec=time.time() - t0,
            reason=f"training crashed: {type(e).__name__}: {e}",
        )

    if time.time() - t0 > time_budget_sec:
        return LOOFilterResult(
            passed=False, demos_memorized=0, held_out_correct=False,
            elapsed_sec=time.time() - t0,
            reason=f"training exceeded budget",
        )

    # Count how many training demos were actually memorized.
    demos_mem = 0
    for ex in train_only.train:
        inp = grid_to_onehot(ex.input).to(device)
        try:
            pred_logits = predict_volcan(
                model, inp, phase_a_max=phase_a_max, phase_b_steps=phase_b_steps
            )
            pred_grid = onehot_to_grid(pred_logits.cpu())
            if grids_equal(pred_grid, ex.output):
                demos_mem += 1
        except Exception:
            pass

    # THE load-bearing test: held-out prediction.
    held_out_correct = False
    try:
        inp = grid_to_onehot(held_out.input).to(device)
        pred_logits = predict_volcan(
            model, inp, phase_a_max=phase_a_max, phase_b_steps=phase_b_steps
        )
        pred_grid = onehot_to_grid(pred_logits.cpu())
        held_out_correct = grids_equal(pred_grid, held_out.output)
    except Exception:
        pass

    elapsed = time.time() - t0
    passed = held_out_correct and elapsed <= time_budget_sec

    reason = ""
    if not passed:
        pieces = []
        if not held_out_correct:
            pieces.append(f"LOO prediction wrong (memorized {demos_mem}/{num_train_demos})")
        if elapsed > time_budget_sec:
            pieces.append(f"budget {elapsed:.0f}s > {time_budget_sec:.0f}s")
        reason = "; ".join(pieces)

    return LOOFilterResult(
        passed=passed,
        demos_memorized=demos_mem,
        held_out_correct=held_out_correct,
        elapsed_sec=elapsed,
        reason=reason,
    )
